version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"   # Expose MariaDB to your laptop
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
